context:
  version: "1.5.5"

recipe:
  name: whisper-cpp
  version: ${{ version }}

source:
  url: https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 27fa5c472657af2a6cee63de349a34b23d0f3781fa9b8ef301a940cf64964a79

outputs:
  - package:
      name: whisper-cpp

    requirements:
      build:
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - sdl2
    build:
      script: |
        cmake -GNinja -S . -B build ${CMAKE_ARGS} -DWHISPER_SDL2=ON \
          -DWHISPER_BUILD_EXAMPLES=ON -DWHISPER_METAL_EMBED_LIBRARY=ON
        cmake --build build
        cmake --install build

        install build/bin/main $PREFIX/bin/whisper-cpp
        install build/bin/server $PREFIX/bin/whisper-cpp-server
        install build/bin/stream $PREFIX/bin/whisper-cpp-stream
        install build/bin/talk $PREFIX/bin/whisper-cpp-talk
        install build/bin/talk-llama $PREFIX/bin/whisper-cpp-talk-llama

  - package:
      name: whisper-cpp-base-en
      version: 0.1.0

    source:
      url: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin?download=true
      sha256: a03779c86df3323075f5e796cb2ce5029f00ec8869eee3fdfb897afe36c6d002
      file_name: ggml-base.en.bin

    requirements:
      run:
        - whisper-cpp

    build:
      noarch: generic
      script:
        - mkdir -p $PREFIX/share/models/whisper-cpp
        - cp ./ggml-base.en.bin $PREFIX/share/models/whisper-cpp/ggml-base.en.bin