recipe:
  name: whisper-cpp
  version: 1.5.4

source:
  url: https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.4.tar.gz
  sha256: 06eed84de310fdf5408527e41e863ac3b80b8603576ba0521177464b1b341a3a

outputs:
  - package: 
      name: whisper-cpp
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - make
      host:
        - sdl2
    build:
      script:
        - make -j${CPU_COUNT}
        - make -j${CPU_COUNT} stream
        - mkdir -p $PREFIX/bin
        - cp main $PREFIX/bin/whisper-cpp
        - cp stream $PREFIX/bin/whisper-cpp-stream
        # forcibly add rpath to the binary
        - install_name_tool -add_rpath $PREFIX/lib $PREFIX/bin/whisper-cpp-stream
        - cp ./ggml-metal.metal $PREFIX/bin/

  # - package:
  #     name: whisper-cpp-base-en
  #   requirements:
  #     run:
  #       - whisper-cpp
  #   build:
  #     script:
  #       - ./models/download-ggml-model.sh base.en
  #       - mkdir -p $PREFIX/share/whisper-cpp/models
  #       - cp ./models/ggml-base.en.bin $PREFIX/share/whisper-cpp/models/ggml-base.en.bin