recipe:
  name: whisper-cpp
  version: 1.5.4

source:
  url: https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.4.tar.gz
  sha256: 06eed84de310fdf5408527e41e863ac3b80b8603576ba0521177464b1b341a3a

outputs:
  - package:
      name: whisper-cpp

    requirements:
      build:
        - ${{ compiler('cxx') }}
        - make
      host:
        - sdl2
    build:
      script:
        - make -j${CPU_COUNT}
        - make -j${CPU_COUNT} stream
        - mkdir -p $PREFIX/bin
        - cp main $PREFIX/bin/whisper-cpp
        - cp stream $PREFIX/bin/whisper-cpp-stream
        # forcibly add rpath to the binary
        # - install_name_tool -add_rpath $PREFIX/lib $PREFIX/bin/whisper-cpp-stream
        - cp ./ggml-metal.metal $PREFIX/bin/

  - package:
      name: whisper-cpp-base-en
      version: 0.1.0
    source:
      url: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin?download=true
      sha256: a03779c86df3323075f5e796cb2ce5029f00ec8869eee3fdfb897afe36c6d002
      file_name: ggml-base.en.bin

    requirements:
      run:
        - whisper-cpp

    build:
      script:
        - mkdir -p $PREFIX/share/whisper-cpp/models
        - cp ./ggml-base.en.bin $PREFIX/share/models/whisper-cpp/ggml-base.en.bin