[project]
name = "whisper"
channels = ["../output", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "whisper-cpp-stream -m $CONDA_PREFIX/share/whisper-cpp/models/ggml-base.en.bin"
convert = "ffmpeg -ar 16000 -ac 1 -c:a pcm_s16le output.wav -i "
transcribe = "whisper-cpp -m $CONDA_PREFIX/share/whisper-cpp/models/ggml-base.en.bin"
download_example = "curl -o speech.wav https://upload.wikimedia.org/wikipedia/commons/7/75/Marshall_Plan_Speech.wav"

[dependencies]
whisper-cpp-base-en = "*"
ffmpeg = ">=6.1.1,<6.2"
whisper-cpp = ">=1.5.4,<1.6"
