[project]
name = "resnet"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["../output", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
download-1 = { cmd = "wget https://raw.githubusercontent.com/NVIDIA/NeMo/263a30be71e859cee330e5925332009da3e5efbc/scripts/tts_dataset_files/heteronyms-052722 -qO heteronyms", outputs = ["heteronyms"] }
download-2 = { cmd = "wget https://raw.githubusercontent.com/NVIDIA/NeMo/263a30be71e859cee330e5925332009da3e5efbc/scripts/tts_dataset_files/cmudict-0.7b_nv22.08 -qO cmudict-0.7b", outputs = ["cmudict-0.7b"] }
download-image-classes = { cmd = "wget https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt", outputs = ["imagenet_classes.txt"] }

detect = { cmd = "python detect.py", depends_on = ["download-image-classes"] }


[dependencies]
pytorch = "*"
jupyterlab = ">=4.1.6,<4.2"
pillow = ">=10.3.0,<10.4"
librosa = ">=0.10.1,<0.11"
scipy = ">=1.13.0,<1.14"
unidecode = ">=1.3.8,<1.4"
inflect = ">=7.0.0,<7.1"
numpy = ">=1.26.4,<1.27"
matplotlib = ">=3.8.4,<3.9"
wget = ">=1.21.4,<1.22"
libsndfile = ">=1.2.2,<1.3"
python = "3.12.*"
torchvision = ">=0.16.1,<0.17"
